### ISSUE TITLE
1.7.10 Swets Instant Disappearance Upon Contact with Water

### ISSUE THREAD

**Issue by ElevenWords** [gildedgames/aether-issues#390]
When a swet touches water in the Aether, it immediately dissapears.

**Comment by roket333** [comment]
I believe this has always been a feature because sweats are 99.99% water.

On Mon, Feb 16, 2015 at 10:17 PM, ElevenWords <notifications@github.com>
wrote:

> When a swet touches water in the Aether, it immediately dissapears.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gildedgames/aether-issues/issues/390>.
>



-- 
http://signaturecraft.us/signatures/eJwrs9OLcnNzEtNLkpMK0kt4ipCE3BIz03MzNFLzs-FSBkbG3OFpCbmKrjlF5UUpRYXKxhxBZfmFWUWp3IZmZqCsQGXAQDJYh4C.png

**Comment by Collin1971** [comment]
This is intentional. I've tweaked the death animation to make this seem more intentional. :)
