### ISSUE TITLE
Cloud Network = false  @ default

### ISSUE THREAD

**Issue by conetopia** [gildedgames/aether-issues#393]
Cloud Network = false
This is set default in server properties.
Is there a possible way to set it true, so the server generates a fresh version with it listed as true?
Running Multicraft and its causing a glitch to organize the server properties, causing the Cloud Network to be at the top of the list or bottom of the list, and nothing shows up on the cloud network list.

It used to when I did normal cauldron hosting on my pc, but using the self hosted multicraft... thats the only problem.

**Comment by xJonL** [comment]
If you really wanted to be organized, you can type the arguments manually. The order doesn't matter.

cloud-visible=true
cloud-name=Aether II Server
cloud-description=Cloud Desc

**Comment by conetopia** [comment]
I assumed that, but that however is not the case.
Not sure what the problem is just yet.
I had this issue last night again, something is causing the system properties to not trigger certain things I think for some odd reason. I will be watching a little more carefully now that i have a few days off work.

**Comment by Collin1971** [comment]
If you're running Windows, you should just be able to add a batch file with the following commands:

echo cloud-visible=true >> [server.properties path]
echo cloud-name=Aether II Server >> [server.properties path]
echo cloud-description=Cloud Desc >> [server.properties path]

We turned off cloud visibility by default because many private servers were getting listed on the cloud and it seemed a little bit invasive.
