### ISSUE TITLE
Move accessories tab

### ISSUE THREAD

**Issue by FyeRee** [gildedgames/aether-issues#404]
If you move the accessories tab to where mods like baubles and galacticraft have their player tabs ( http://i.imgur.com/qZg50L7.png ) you could do away with the backpack tab and make the mod fit better with others

**Comment by Brenwwe** [comment]
We use our custom tab system built into Gilded Games Util which allows for more customisation compared to the Tinkers Construct tab system used in Galacticraft. Our system is open source so other mod developers are very welcome to use our system.

**Comment by roket333** [comment]
What's that D-Coin looking tab for? what does it do? what mod is i added by?

**Comment by xJonL** [comment]
That's the donator tab. When you donator to Aether II, you receive coesmetic Moa skins

**Comment by Collin1971** [comment]
We have no plans on changing this. Changing the way inventory tabs work would make the chat tabs look inconsistent.

**Comment by Stekeblad** [comment]
Can I add something to this issue instead of opening a new one? This is also about the accessories tab.

If you have not changed your mind on moving the tabs, some changes to it may be good.
The tabs are overlapping NEI and tool tips. The item subset button is not very important, you can still press it without a problem, but the fact that the tabs are above the tool tips is annoying, I guess it is a small and quick change to make it render below the tool tip (so the tool tip hides the tabs) but otherwise appears as normal.
![2016-08-14_22 47 14](https://cloud.githubusercontent.com/assets/12627375/17651976/062b5238-6272-11e6-9b88-891626743b5b.png)

aether-1.7.10-1.6 on project ozone 2 version 0.1.4
