### ISSUE TITLE
Factorization Colossus Crash

### ISSUE THREAD

**Issue by MoreThanHidden** [gildedgames/aether-issues#469]
Hi There,

Issue:
Destroying blocks on the new Colossus added by factorization results in the following crash..

Mod Versions:
Aether Version: 1.7.10-1.1
Gilded Games Version: 1.7.10-1.1
Factorization Version: 0.8.88.8.8888

Crash:
https://gist.github.com/MoreThanHidden/187de5b5900c12f674e1

**Comment by Collin1971** [comment]
I've compiled a version of Gilded Games Util without Threaded Lighting. (warning: I haven't tested it.)

You can grab it here: https://collin1971.net/aetherii/files/extras/gilded-games-util-1.7.10-1.6-no-tl.jar

Could you see if this modified version works?

**Comment by MoreThanHidden** [comment]
Thanks, Seems to have stopped it from crashing on my client, Will there be anything missing without the Threaded Lighting?

**Comment by Collin1971** [comment]
Threaded Lighting is an previously-optional mod that made lighting calculations in Minecraft much faster on processors with more than one core. Minecraft's lighting system is really slow in the Aether due to all the surface area of the islands and other factors I don't quite understand.

So, no. You shouldn't be missing out on any features. It's purely for performance. The Colored Lights mod you have installed may already have it's own "Threaded Lighting" though.
