### ISSUE TITLE
Cauldron server crash aether 1.7.10-1.2 and 1.7.10-1.4

### ISSUE THREAD

**Issue by Sticklilu** [gildedgames/aether-issues#509]

**Comment by Sticklilu** [comment]
Hello,
I'm french and I have a problem with my cauldron server with the 1.7.10-1.4 version of aether. I have the same problem from the 1.7.10-1.2 and I thought it was going to be corrected,  so here is the log :  http://pastebin.com/hf5VXEA3

For information I use Java 7 and I have the 1.7.10-1.1207.01.198 version of cauldron.
Thanks for your time and your attention.

**Comment by DynamicMC** [comment]
Try build 1448.121 from here http://tcpr.ca/cauldron

**Comment by Sticklilu** [comment]
You're the best ! It work again !

**Comment by Collin1971** [comment]
Please do not directly link to sites mirroring DMCA'd content here.

While the maintainers have good intention (and I have no reason to believe otherwise), the content may not be 100% safe for human consumption, and (as of the time of writing this) still not released [from the DMCA claims](https://github.com/github/dmca/blob/master/2014-09-05-CraftBukkit.md) made by Wesley Wolfe.

Discussion relating to or linking to DMCA'd content will be _removed_.
