### ISSUE TITLE
Phygs and Flying Cows "Lag"

### ISSUE THREAD

**Issue by CA2020** [gildedgames/aether-issues#518]
I'm having a problem with the Flying Cows and Phygs

It generates some kind of lag / game freezing every few blocks you advance. I will attach a video that will be the easier way to describe and see the problem. If you watch the video, you can see some lag on the start, but that happens always on new worlds, and worst when spawn on a jungle. 

Also attach images with messages showing on the console while this happens. I get this messages when playing a mid size ModPack with around 60 mods. But it also happens but not that frequent when playing with just Minecraft, Aether and Animal Bikes (used Animal Bikes, just to show that this flying animals cause the same issue)
Also this happens when flying into new chunks and not on already generated ones.

I was not sure the best option to share the video with you guys, so I uploaded it to Mediafire
http://www.mediafire.com/watch/eq4hrteng1nxkgl/Video.avi

Some PC Details:
Motherboard ASUS Z97-K [CSM]
2 x 4Gb - DDR3 Kingstone HyperX
ASUS NVidia GeForce GTX 750 [1Gb]
Intel Core i5-4690 LGA1150

![dosmods](https://cloud.githubusercontent.com/assets/7746836/8606936/bf0bb90e-2665-11e5-9165-b46688f3981c.png)
![dosmods2](https://cloud.githubusercontent.com/assets/7746836/8606937/bf11b6e2-2665-11e5-870d-f025944aeb9d.png)
![mods](https://cloud.githubusercontent.com/assets/7746836/8606938/bf1342be-2665-11e5-9b73-e1148ddd02df.png)

**Comment by 115kino** [comment]
Flying cows and Phyg's try their best to keep up with server/client the screenshots taken of console don't really point to anything specific other than Threaded lighting preventing lag for a certain ammount of time, The client might have too much to process at a time with generating new terrain and keeping track of everything else it needs to do. I can't say much about the 60 mods since I don't know if they altar or add anything new to the terrain.

**Comment by Collin1971** [comment]
> Can't keep up! Did the system time change, or is the server overloaded? Running (ms) behind, skipping (ticks)

It seems that your computer can't support all the mods you're running and keep running at 20 ticks/sec (which is odd, because your computer is fairly powerful).

Usually, Minecraft runs at 20 ticks/sec. Which means every 0.05 seconds, Minecraft progresses the game forward a small bit. That involves updating entities, growing crops, hunger depletes and health regenerates, etc.

When adding more mods, Minecraft tends to have to do a lot more in those precious 0.05 seconds it has for each tick. If it isn't able to fully finish calculating everything, the next tick is delayed, and you get "lag".

When flying around on phygs/flying cows, you're probably generating a lot of new chunks, causing the available processing power to be instead used for chunk generation, causing the "lag" you describe since Minecraft can't update the game fast enough.

You should try turning down your render distance, removing some mods, or installing a mod like OptiFine.
