### ISSUE TITLE
Aether Portal Not  Working

### ISSUE THREAD

**Issue by MsFinalFantasy9** [gildedgames/aether-issues#577]
When i build the portal, and then put water in it, it doesnt work (It doesnt make it a portal.)

**Comment by Tamaized** [comment]
More information could help the Authors out here, such as Forge version, Aether version, and a mod list.

**Comment by MsFinalFantasy9** [comment]
the forge version thats compatible with the most recent aether. 
I use the launcher.

**Comment by Collin1971** [comment]
We need _specifics_. Please upload your Forge logs (found in `%APPDATA%/.aether/profiles/1.7.10-1.5.2/logs/latest.log`) to [GitHub Gist](https://gist.github.com).

**Comment by SkyLord570** [comment]
I have this same problem however, when I place the water down on the glowstone blocks it crashes the game. I downloaded the mods and inputted them into a modpack known as bytesyze on a 1.7.10 version with extra mods like Schematica and its required mods, world edit, and shaders mod with its required mods. I don't know if I should add the latest log from the modpack folder?

**Comment by Collin1971** [comment]
@SkyLord570: That bug sounds like you're running an old version of Forge (we get the same bug report from dozens of people, Forge changed how the fluid registry works, breaking our bucket code on old versions). Either **update the Forge version** in your modpack, or post your `latest.log` you mentioned.

**Comment by Tamaized** [comment]
I'd like to know how you even managed to load up a world with both Aether and Schematica, while I was in my dev workspace a few days ago with the 2 mods I had encountered a NPE crash.

And here's a log from a normal Minecraft Forge instance with just the 2 mods in case you wanted to see it.
https://gist.github.com/Tamaized/70d72caaaebe80164526

**Comment by Collin1971** [comment]
@Tamaized Lunatrius made a PR to GGUtil fixing the issue you're having quite a while ago, and I forgot to backport it to our 1.7 branch. Sorry about that. You can grab version 1.7.10-1.8 of Gilded Games Util [here](http://files.aetherii.com/files/versions/1.7.10-1.5.2/gilded-games-util-1.7.10-1.8.jar).

**Comment by Tamaized** [comment]
Very nice, didn't even know there was a Github setup for GildedGamesUtil, silly me.

**Comment by SkyLord570** [comment]
@Collin1971 That's a good idea with forge. The modpack has asked to update and I have refused because I don't want it to change some of my worlds and stuff but I guess I can just back it up. I'll send the latest.log just in case it's more than the forge not being up to date. If I could ask do you want the latest.log file from forge, aether II, or the whole mod pack?

@Tamaized Schematica has a support mod known as Lunastrius Core, I don't recall anything about it interfering with Aether 2's support mod. Considering Schematica takes block ID's and save them in a dilated spot to be reused. That's from own experience. You said when you load the world it crashed, you either didn't have the support mod on, also I was thinking you meant when you opened your schematics folder and placed one schematic down it crashed in game so I didn't see a clear thing...

**Comment by Tamaized** [comment]
@SkyLord570 Collin1971 had already referenced the reason for my crash.
