### ISSUE TITLE
Aether II: Items "Texture Fail/Error"

### ISSUE THREAD

**Issue by Teodor3** [gildedgames/aether-issues#579]
I've downloaded the launcher and almost all my items are bugged, they appear like a "texture error image". I don't know really how explain, but I can't see them! It's hard to play because I can't know which item is, only by the name. But anyway, it's ugly and horrible. If someone knows how do I fix this, please tell me. I tried to re-install the launcher, didn't work, etc. I tried the manual download, but it's a confusion, I can't download, it doesn't work, I don't know the mods that needs to run the Aether, etc. I just wanna know how to fix this glitch that is happening to me.
Hope you understand,
~Teodor 
<img width="1440" alt="captura de tela 2015-11-18 as 19 40 21" src="https://cloud.githubusercontent.com/assets/15915217/11255658/918b588c-8e2e-11e5-88f4-ddad0657ed1a.png">

**Comment by Tamaized** [comment]
Looks to be the same issue as #516

**Comment by Collin1971** [comment]
This is a bug caused by Forge's new loading screen (apparently some Mac hardware throws up and reuses texture data laying around in memory). You can disable it as so:

- Create a new file called `splash.properties` in the `config` folder where the Aether II is installed (in your case, `/Users/USERNAME/Library/Application Support/.aether/profiles/1.7.10-1.5.1/config`)
- Add the line `enabled=false` to the properties file.
- Save and restart your game.

**Comment by Teodor3** [comment]
I can't, it says "splash.properties" is already being used
