### ISSUE TITLE
Labyrinth pillars and carved labyrinth pillars aren't affected by skyroot's double drops.

### ISSUE THREAD

**Issue by BloodbirdX** [gildedgames/aether-issues#591]

**Comment by Collin1971** [comment]
This is a technical issue.

Skyroot's double drops work by setting metadata on mined blocks, which prevents you from repeatably getting double drops on one block. Unfortunately, the pillars use metadata to store their rotation (1 through 12), which prevents us from storing our additional metadata (it would require 24 unique metadata values, and only 15 are available per block).

In the 1.8 rewrite, this issue is irrelevant because we use our own method (without the use of metadata) to make any block minable with a wooden pickaxe eligible for double drops.

As such, this issue won't, and cannot be fixed in 1.7.
