### ISSUE TITLE
Skyroot Tool Ability Doesn't Work On Overworld Blocks

### ISSUE THREAD

**Issue by sliderhostmimic** [gildedgames/aether-issues#613]
The double drop ability of skyroot tools doesnt work on blocks in the overworld, if you mine any block in the overworld with a skyroot tool you will only get 1 of that item. 

I'm not sure if this is actually a bug or if its intended. the only reason i'm posting this is because i noticed the abilities of holystone and gravitite tools work in the overworld, so if they work in the overworld, shouldnt skyroot tools work as well?

**Comment by Collin1971** [comment]
This doesn't work in 1.7 because we store special metadata on our blocks to mark them as "mined", and we're unable to modify the metadata of vanilla blocks.

In the 1.8 rewrite of the Aether, Skyroot Tools work properly on every block as we store special data within chunks to mark whether or not blocks are placed, rather than using metadata.
